language: julia

os:
  - linux

addons:
  apt:
    packages:
      - graphviz
      - ttf-dejavu

julia:
  - 1.0
  - 1.4
  - nightly

notifications:
  email: false

jobs:
  allow_failures:
    - julia: nightly
  include:
    - stage: "Documentation"
      julia: 1.0
      script:
        - julia --project=doc/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd()));
                                              Pkg.instantiate()'
        - julia --project=doc/ doc/make.jl
