name = "SemanticModels"
uuid = "f5ac2a72-33c7-5caf-b863-f02fefdcf428"
authors = ["James Fairbanks <james.fairbanks@gtri.gatech.edu>", "Micah Halter <micah.halter@gtri.gatech.edu>"]
version = "0.4.0"

[deps]
Catlab = "134e5e36-593f-5add-ad60-77f754baafbe"
LightGraphs = "093fc24a-ae57-5d10-9952-331d41423f4d"
MacroTools = "1914dd2f-81c6-5fcd-8719-6d5c9610ff09"
Petri = "4259d249-1051-49fa-8328-3f8ab9391c33"

[compat]
Catlab = "^0.7.0"
LightGraphs = "^1.3.3"
MacroTools = "^0.5.5"
Petri = "^1.0.0"
julia = "1.0"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
